const productsData = [
  {
    id: "1",
    name: "Resident Evil 4",
    price: 16000,
    category: "Game",
    brand: "Capcom",
    imageURL: "p1",
    description: "Resident Evil 4 Remake is an exhilarating reimagining of the iconic survival horror game that revolutionized the genre. Set in a sinister rural village in Europe, the game follows the intense and gripping journey of Leon S. Kennedy, a government agent on a mission to rescue the U.S. President's daughter, Ashley Graham, from a mysterious cult. With stunning next-generation graphics and enhanced gameplay mechanics, Resident Evil 4 Remake delivers a truly immersive experience. Players will be captivated by the detailed environments, lifelike character models, and atmospheric lighting, which heighten the sense of dread and suspense throughout the game.The Remake introduces modernized controls and camera perspectives, providing a more intuitive and seamless gameplay experience. Engage in intense combat encounters as you face hordes of relentless enemies, including grotesque creatures infected by a sinister parasite. Utilize a vast arsenal of weapons, clever tactics, and resource management to survive the relentless onslaught.",
  },
  {
    id: "2",
    name: "Samsung S21+",
    price: 320000,
    category: "Phone",
    brand: "Samsung",
    imageURL: "p2",
    description: "The Samsung Galaxy S21+ is a top-tier smartphone that delivers a premium experience. Its sleek design and vibrant display offer a visually stunning experience. The camera system captures incredible photos and videos with exceptional detail and dynamic range. The powerful processor ensures smooth performance and seamless multitasking. The large battery provides long-lasting usage, and fast charging capabilities keep you powered up in no time. The 5G connectivity opens up a world of possibilities, enabling faster downloads and smoother streaming. With its impressive features and high-quality build, the Samsung S21+ is a fantastic choice for those seeking a top-of-the-line smartphone. ",
  },
  
  {
    id: "3",
    name: "Iphone 14",
    price: 320000,
    category: "Phone",
    brand: "Apple",
    imageURL: "p3",
    description: "The iPhone 14 is a remarkable device that pushes the boundaries of innovation. With its sleek design and stunning display, it offers an immersive visual experience. The camera system has been enhanced, capturing breathtaking photos and videos with impressive clarity and depth. The processing power has been upgraded, delivering seamless performance and smooth multitasking. The battery life has also seen improvements, allowing for extended usage without frequent charging. Additionally, the introduction of new features like augmented reality capabilities and advanced security measures further enhances the overall user experience. The iPhone 14 sets a new standard for smartphones, combining cutting-edge technology with Apple's signature style and reliability",
  },
  {
    id: "4",
    name: "Split Air conditioner",
    price: 320000,
    category: "Electronic",
    brand: "Thermocool",
    imageURL: "p4",
    description: "The Thermocool split air conditioner is a reliable and efficient cooling solution for any space. With its sleek and compact design, it seamlessly blends into any room decor. The air conditioner provides powerful cooling performance, quickly cooling down the room even on hot summer days. The energy-saving features help reduce electricity consumption, making it environmentally friendly and cost-effective. The remote control offers convenience, allowing users to easily adjust temperature and fan speed from anywhere in the room. With its low noise operation, the Thermocool split air conditioner ensures a peaceful and comfortable environment. Overall, it's a great choice for anyone seeking reliable and efficient cooling.",
  },
  {
    id: "5",
    name: "The Last of us Part 1",
    price: 16000,
    category: "Game",
    brand: "Naughty Dog",
    imageURL: "p5",
    description: "The Last of Us Part 1 is an extraordinary and emotionally charged action-adventure game that takes players on a harrowing journey through a post-apocalyptic world. Set in a world devastated by a fungal infection, you follow the story of Joel, a hardened survivor, and Ellie, a young girl. Together, they must navigate treacherous landscapes, confront dangerous factions, and face unimaginable horrors in their quest for survival. With its immersive storytelling, gripping gameplay, and breathtaking visuals, The Last of Us Part 1 delivers an unforgettable experience that explores the depths of human resilience, love, and sacrifice in the face of overwhelming adversity.",
  },
  {
    id: "6",
    name: "Luxury Handbag",
    price: 12000,
    category: "Fashion",
    brand: "Bora",
    imageURL: "p6",
    description: "The Luxury Handbag is the epitome of elegance and sophistication. Crafted with impeccable attention to detail and using only the finest materials, it exudes luxury from every angle. The exquisite design, combined with meticulous craftsmanship, makes it a standout accessory. The spacious interior offers ample storage for essentials, while the well-organized compartments help keep belongings in order. The luxurious finishes, such as premium leather, exquisite hardware, and intricate stitching, showcase the handbag's exceptional quality. With its timeless style and impeccable construction, the Luxury Handbag is a statement piece that adds a touch of opulence and refinement to any outfit, making it a coveted item for discerning fashion enthusiasts.",
  },
  {
    id: "7",
    name: "Deep Freezer",
    price: 420000,
    category: "Electronics",
    brand: "Thermocool",
    imageURL: "p7",
    description: "The deep freezer is an essential appliance for any home or business that requires extra storage for frozen goods. With its spacious interior and efficient cooling system, it offers ample space to store a large quantity of frozen items, such as meats, vegetables, and prepared meals. The deep freezer's temperature control allows for precise settings, ensuring optimal freezing and preservation of food items. Its durable construction and sturdy build guarantee long-lasting performance. The freezer's organized shelving and storage baskets make it easy to locate and access items. With its reliable freezing capabilities and generous capacity, the deep freezer is a reliable companion for keeping food fresh and extending its shelf life.",
  },
  {
    id: "8",
    name: "Rolex Gold",
    price: 220000,
    category: "Fashion",
    brand: "Rolex",
    imageURL: "p8",
    description: "The Rolex Gold Watch is the epitome of luxury and craftsmanship. Its stunning design, featuring a rich gold casing and a classic bracelet, exudes elegance and sophistication. The precision and attention to detail in the watch's construction are evident in every aspect, from the intricate dial to the smooth movement of the hands. The gold material not only adds a touch of opulence but also ensures durability and longevity. The watch's reliability and accuracy are unmatched, thanks to its high-quality Swiss-made movement. Owning a Rolex Gold Watch is a statement of status and refinement, making it a prized possession for watch enthusiasts and connoisseurs alike.",
  },
  {
    id: "9",
    name: "Boots",
    price: 16000,
    category: "Fashion",
    brand: "Timberland",
    imageURL: "p9",
    description: "The Brown Timberland Boot is a timeless and reliable footwear choice for any outdoor enthusiast. Crafted with premium quality materials, it offers durability and longevity. The rich brown color adds a touch of rugged elegance, making it suitable for both casual and semi-formal occasions. The boot features a sturdy construction and a comfortable fit, providing excellent support and traction on various terrains. The waterproof capabilities ensure your feet stay dry in wet conditions, while the insulation keeps you warm during colder months. With its iconic design and exceptional performance, the Brown Timberland Boot is a classic choice that blends style and functionality seamlessly.",
  },
  {
    id: "10",
    name: "PlayStation 4",
    price: 180000,
    category: "Game",
    brand: "Sony",
    imageURL: "p10",
    description: "The PlayStation 4 is a gaming console that continues to impress with its vast library of games and exceptional performance. Its sleek design fits well in any entertainment setup. The graphics and processing power deliver stunning visuals and smooth gameplay, enhancing the overall gaming experience. The DualShock 4 controller offers precise control and comfortable handling, immersing players in the action. The PlayStation 4's online capabilities allow for multiplayer gaming and access to a wide range of digital content. With its impressive game selection, powerful performance, and online features, the PlayStation 4 remains a fantastic choice for both casual and hardcore gamers.",
  },
  {
    id: "11",
    name: "Office Leather Handbag-black",
    price: 12000,
    category: "Fashion",
    brand: "Bora",
    imageURL: "p11",
    description: "The black leather office handbag is a sophisticated and versatile accessory that elevates any professional ensemble. Crafted with high-quality leather, it exudes elegance and durability. The spacious interior accommodates essentials like a laptop, documents, and personal items, while multiple compartments help with organization. The sleek black color adds a touch of professionalism, making it suitable for both formal meetings and everyday use. The sturdy handles and detachable shoulder strap offer flexibility and comfort during commutes. With its timeless design and practicality, the black leather office handbag is a must-have for the modern working woman, combining style and functionality seamlessly.",
  },
  {
    id: "12",
    name: "Office Leather Handbag-brown",
    price: 12000,
    category: "Fashion",
    brand: "Bora",
    imageURL: "p12",
    description: "The Office Leather Handbag in brown is a stylish and sophisticated accessory that exudes professionalism and elegance. Crafted with high-quality leather, it boasts durability and a luxurious feel. The sleek black color complements any outfit, making it versatile for both formal and casual settings. The spacious interior is designed to accommodate a laptop, documents, and other essentials, while the various compartments and pockets help keep items organized. The sturdy handles and detachable shoulder strap offer comfortable carrying options. With its timeless design and practicality, the Office Leather Handbag in black is a perfect companion for the modern professional, combining style, functionality, and durability effortlessly.",
  },
  
  {
    id: "13",
    name: "Samsung Galaxy S23 Ultra",
    price: 820000,
    category: "Phone",
    brand: "Samsung",
    imageURL: "p13",
    description: "'The Samsung Galaxy S23 Ultra takes Samsung's flagship to the next level with a whopping 200MP camera and lots of other photography improvements. You also get a Qualcomm Snapdragon 8 Gen 2 chip for Galaxy for the fastest speed on Android, stellar battery life and smart One UI 5.1 upgrades.'...Tom's Guide",
  },
  {
    id: "14",
    name: "Sexy Ladies' Heels",
    price: 7000,
    category: "Fashion",
    brand: "Sandras",
    imageURL: "p14",
    description: "The multi-colored high heel shoe for a lady by Sandras is a stunning and vibrant footwear choice that adds a pop of personality to any outfit. With its playful combination of colors, it exudes confidence and individuality. The high heel design elongates the legs and provides a flattering silhouette. The shoe's construction ensures comfort and stability, allowing for hours of wear without sacrificing style. Whether paired with a little black dress or a tailored suit, this shoe instantly becomes the focal point of any ensemble. With its eye-catching colors and fashionable appeal, the multi-colored high heel shoe is a must-have for fashion-forward women looking to make a statement.",
  },
  
  {
    id: "15",
    name: "Switch",
    price: 220000,
    category: "Game",
    brand: "Nintendo",
    imageURL: "p15",
    description: "The Nintendo Switch is a versatile and innovative gaming console that offers a unique gaming experience. Its hybrid design allows for both handheld and docked gameplay, catering to different gaming preferences. The console's library of games is extensive, ranging from beloved Nintendo classics to third-party titles. The Joy-Con controllers provide intuitive and immersive gameplay, with motion controls adding an extra layer of interactivity. The console's portability makes it ideal for gaming on the go, while the option to dock it to a TV delivers a more traditional console experience. With its exceptional game lineup and flexibility, the Nintendo Switch is a must-have for gamers of all ages",
  },
  {
    id: "16",
    name: "Xbox Series X",
    price: 420000,
    category: "Electronics",
    brand: "Microsoft",
    imageURL: "p16",
    description: "The Xbox Series X is a powerhouse gaming console that offers a next-level gaming experience. With its sleek design and powerful hardware, it delivers stunning graphics and smooth gameplay. The console's fast load times and quick resume feature ensure minimal interruptions and maximum immersion. The extensive library of games, including exclusive titles and backward compatibility, offers a diverse range of options for every gaming preference. The Xbox Game Pass subscription service provides access to a vast collection of games, further enhancing the gaming experience. With its advanced features and impressive performance, the Xbox Series X sets a new standard for console gaming, making it a must-have for avid game.",
  },
  {
    id: "17",
    name: "Classy Ladies' Slippers",
    price: 7000,
    category: "Fashion",
    brand: "Sandras",
    imageURL: "p17",
    description: "The Classy Ladies' High Heel Slippers are a perfect blend of style and comfort. Crafted with attention to detail, these slippers exude elegance and sophistication. The high heel design adds a touch of glamour while elongating the legs for a flattering look. The soft and cushioned insole provides all-day comfort, making them suitable for extended wear. The sleek and minimalistic design complements various outfits, from casual to formal. Whether attending a special event or enjoying a night out, these slippers are the ideal choice for fashion-forward women who want to make a statement. With their classy appeal and comfortable fit, they are a must-have addition to any shoe collection.",
  },
  {
    id: "18",
    name: "Home Theater",
    price: 46000,
    category: "Electronics",
    brand: "Djack",
    imageURL: "p18",
    description: "The Djack Home Theater Sound System is a powerhouse of audio performance. With its immersive surround sound capabilities and impressive bass output, it elevates the home entertainment experience to new heights. The system includes multiple speakers and a subwoofer, creating a dynamic and balanced audio experience. The connectivity options, including Bluetooth, USB, and AUX inputs, allow for easy connection to various devices. The sleek and modern design adds a touch of sophistication to any living space. Whether enjoying movies, music, or gaming, the Djack Home Theater Sound System delivers rich and clear sound that brings the entertainment to life.",
  },
  {
    id: "19",
    name: "Sexy Ladies' Cross Strap",
    price: 7000,
    category: "Fashion",
    brand: "Sandras",
    imageURL: "p19",
    description: "The Sexy Ladies' Cross Strap high heel shoe is a show-stopping footwear choice for those looking to make a bold and stylish statement. Crafted with attention to detail, these heels feature a seductive cross strap design that adds a touch of allure. The high heel elevates any outfit, elongating the legs and providing a confident stride. The comfortable cushioned insole ensures all-day comfort, making them suitable for various occasions. The versatile design pairs well with dresses, skirts, or even jeans for a fashionable look. With their sexy and captivating appeal, these high heel shoes are a must-have for any fashion-forward woman.",
  },
  {
    id: "20",
    name: "Tecno Camon 20",
    price: 90000,
    category: "Phone",
    brand: "Tecno",
    imageURL: "p20",
    description: "The Tecno Camon 20 is a feature-packed smartphone that offers an impressive photography experience. Its AI-powered quad-camera setup delivers stunning photos and videos with excellent clarity and detail. The 48MP main camera, combined with the ultra-wide-angle lens and macro lens, provides versatile shooting options. The large display with slim bezels offers an immersive viewing experience, perfect for multimedia consumption. The powerful processor ensures smooth performance, enabling seamless multitasking and gaming. The long-lasting battery life keeps you connected throughout the day, while fast charging capabilities minimize downtime. With its affordable price point and impressive camera capabilities, the Tecno Camon 20 is a great choice for photography enthusiasts on a budget.",
  },
  {
    id: "21",
    name: "Oculus Quest 2",
    price: 7000,
    category: "Game",
    brand: "Reality Labs",
    imageURL: "p21",
    description: "The Oculus Quest 2 is a game-changer in the world of virtual reality (VR) gaming. With its wireless and all-in-one design, it offers a truly immersive experience without the need for a PC or external sensors. The high-resolution display provides sharp visuals, while the smooth performance and precise tracking enhance gameplay. The intuitive controllers allow for natural interaction and precise hand tracking. The vast library of games and apps ensures there is something for every VR enthusiast. The Quest 2's comfortable fit, adjustable straps, and ergonomic design make it enjoyable for extended gaming sessions. Overall, the Oculus Quest 2 sets the standard for accessible and high-quality VR",
  },
];
